branches:
  only:
  - source
install:
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.69.2/hugo_0.69.2_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb
script:
- ls -lrtA themes
- hugo version
- hugo -v
deploy:
  local_dir: public
  provider: pages
  skip_cleanup: true
  target_branch: master
  fqdn: 'jmsbrdy.com'
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: source
after_deploy:
  - |
    curl -X DELETE "https://api.cloudflare.com/client/v4/zones/${CF_ZONE_ID}/purge_cache" \
     -H "X-Auth-Email: ${CF_EMAIL}" \
     -H "X-Auth-Key: ${CF_API_KEY}" \
     -H "Content-Type: application/json" \
     --data '{"purge_everything":true}'
