language: go
branches:
  only:
  - source
install:
- go get -v github.com/spf13/hugo
script:
- git clone https://github.com/kakawait/hugo-tranquilpeak-theme.git ./themes/hugo-tranquilpeak-theme
- hugo -v
after_success:
- echo 'jmsbrdy.com' > ./public/CNAME
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
